/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;
import java.awt.Color;
import javax.swing.JOptionPane;
import Entidad.*;
import Datos.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author estrosebas
 */
public class menuunitario extends javax.swing.JFrame {

    /**
     * Creates new form menuunitario
     */
    public menuunitario() {
        initComponents();
        setLocationRelativeTo(null);
        consultaralumnos();
        consultarRepresentantes();
        consultarMatriculas();
        consultarDistritosalum();
        consultarDistritosrepres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        salida = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        multimenus = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        RegistrarAlumnos = new javax.swing.JButton();
        modificarAlumno = new javax.swing.JButton();
        EliminarAlumno = new javax.swing.JButton();
        BuscarAlumno = new javax.swing.JButton();
        HabilidadesAlumno = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        RegistrarRepresentante = new javax.swing.JButton();
        BuscarRepresentante = new javax.swing.JButton();
        modificarRepresentante = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Telefonos = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaMatriculas = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        Registrar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Buscar1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaDistritoAlum = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        RegistrarDistritoAlumno = new javax.swing.JButton();
        modificar1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Buscar2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabladistritorepre = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        Registrar2 = new javax.swing.JButton();
        modificar2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Buscar3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        panelbotonMatriculas = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panelbotonRepresentantes = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelbotonAlumnos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Distritosboton = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(128, 0, 128));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salida.setBackground(new java.awt.Color(255, 255, 255));
        salida.setOpaque(false);
        salida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                salidaMouseMoved(evt);
            }
        });
        salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salidaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salidaMouseExited(evt);
            }
        });
        salida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("X");
        salida.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 18, -1));

        jPanel2.add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Universidad Tecnologica del Perú");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 470, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 680, 100));

        multimenus.setBackground(new java.awt.Color(0, 0, 0,100));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0,100));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(0, 0, 0,100));

        jLabel14.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 3, 36)); // NOI18N
        jLabel14.setText("<html>Bienvenido al <br/>Sistema de matriculas</html>");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 600, 390));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backe.jpg"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 440));

        multimenus.addTab("0", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0,100));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255,100));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido materno", "Apellido paterno", "Dni"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 615, 265));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Alumnos");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0, 100));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrarAlumnos.setText("Registrar");
        RegistrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarAlumnosActionPerformed(evt);
            }
        });
        jPanel7.add(RegistrarAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, -1, -1));

        modificarAlumno.setText("Modificar");
        modificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAlumnoActionPerformed(evt);
            }
        });
        jPanel7.add(modificarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 10, -1, -1));

        EliminarAlumno.setText("Eliminar");
        EliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAlumnoActionPerformed(evt);
            }
        });
        jPanel7.add(EliminarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 10, -1, -1));

        BuscarAlumno.setText("Buscar");
        BuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarAlumnoActionPerformed(evt);
            }
        });
        jPanel7.add(BuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 10, -1, -1));

        HabilidadesAlumno.setText("Habilidades");
        HabilidadesAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabilidadesAlumnoActionPerformed(evt);
            }
        });
        jPanel7.add(HabilidadesAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 10, -1, -1));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 10, -1, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 610, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backe.jpg"))); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 450));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 450));

        multimenus.addTab("1", jPanel5);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel8.setBackground(new java.awt.Color(51, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido materno", "Apellido paterno", "Dni"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla2);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 615, 265));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Representantes");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0, 100));

        RegistrarRepresentante.setText("Registrar");
        RegistrarRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarRepresentanteActionPerformed(evt);
            }
        });

        BuscarRepresentante.setText("Buscar");
        BuscarRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarRepresentanteActionPerformed(evt);
            }
        });

        modificarRepresentante.setText("Modificar");
        modificarRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarRepresentanteActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Telefonos.setText("Telefonos");
        Telefonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonosActionPerformed(evt);
            }
        });

        jButton6.setText("Actualizar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(RegistrarRepresentante)
                .addGap(18, 18, 18)
                .addComponent(BuscarRepresentante)
                .addGap(18, 18, 18)
                .addComponent(modificarRepresentante)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(Telefonos)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(Telefonos)
                    .addComponent(BuscarRepresentante)
                    .addComponent(RegistrarRepresentante)
                    .addComponent(modificarRepresentante)
                    .addComponent(jButton6))
                .addGap(7, 7, 7))
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 610, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backe.jpg"))); // NOI18N
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 670, 450));

        jPanel13.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 440));

        multimenus.addTab("2", jPanel13);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(51, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaMatriculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Matricula", "ID Alumno", "nivel", "grado", "estado", "metodo", "monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablaMatriculas);

        jPanel20.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 615, 265));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Matriculas");
        jPanel20.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel21.setBackground(new java.awt.Color(0, 0, 0, 100));

        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Buscar1.setText("Buscar");
        Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar1ActionPerformed(evt);
            }
        });

        jButton7.setText("Actualizar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Registrar)
                .addGap(18, 18, 18)
                .addComponent(Buscar1)
                .addGap(18, 18, 18)
                .addComponent(modificar)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar)
                    .addComponent(Buscar1)
                    .addComponent(jButton3)
                    .addComponent(Registrar)
                    .addComponent(jButton7))
                .addGap(7, 7, 7))
        );

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 610, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backe.jpg"))); // NOI18N
        jPanel20.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -4, 680, 440));

        jPanel15.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 440));

        multimenus.addTab("3", jPanel15);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(51, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaDistritoAlum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TablaDistritoAlum);

        jPanel11.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 615, 265));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Distrito - Alumnos");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0, 100));

        RegistrarDistritoAlumno.setText("Registrar");
        RegistrarDistritoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarDistritoAlumnoActionPerformed(evt);
            }
        });

        modificar1.setText("Modificar");
        modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar1ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Buscar2.setText("Buscar");
        Buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar2ActionPerformed(evt);
            }
        });

        jButton8.setText("Actualizar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(RegistrarDistritoAlumno)
                .addGap(18, 18, 18)
                .addComponent(Buscar2)
                .addGap(18, 18, 18)
                .addComponent(modificar1)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(89, 89, 89))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar1)
                    .addComponent(jButton4)
                    .addComponent(Buscar2)
                    .addComponent(RegistrarDistritoAlumno)
                    .addComponent(jButton8))
                .addGap(7, 7, 7))
        );

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 610, 40));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backe.jpg"))); // NOI18N
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -4, 680, 440));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 440));

        multimenus.addTab("4", jPanel10);

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(51, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabladistritorepre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabladistritorepre);

        jPanel22.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 615, 265));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Distrito - Representantes");
        jPanel22.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel23.setBackground(new java.awt.Color(0, 0, 0, 100));

        Registrar2.setText("Registrar");
        Registrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar2ActionPerformed(evt);
            }
        });

        modificar2.setText("Modificar");
        modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar2ActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Buscar3.setText("Buscar");
        Buscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar3ActionPerformed(evt);
            }
        });

        jButton9.setText("Actualizar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(Registrar2)
                .addGap(18, 18, 18)
                .addComponent(Buscar3)
                .addGap(18, 18, 18)
                .addComponent(modificar2)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(85, 85, 85))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar2)
                    .addComponent(jButton5)
                    .addComponent(Buscar3)
                    .addComponent(Registrar2)
                    .addComponent(jButton9))
                .addGap(7, 7, 7))
        );

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 610, 40));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backe.jpg"))); // NOI18N
        jPanel22.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -4, 680, 440));

        jPanel18.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 440));

        multimenus.addTab("5", jPanel18);

        jPanel1.add(multimenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 670, 470));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logop.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 80));

        jPanel3.setBackground(new java.awt.Color(0, 128, 128));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setToolTipText("");
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 173, 140, 10));

        panelbotonMatriculas.setBackground(new java.awt.Color(0, 128, 128));
        panelbotonMatriculas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelbotonMatriculas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelbotonMatriculasMouseMoved(evt);
            }
        });
        panelbotonMatriculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelbotonMatriculasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelbotonMatriculasMouseExited(evt);
            }
        });
        panelbotonMatriculas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Matriculas");
        panelbotonMatriculas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 32, 80, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matricula.png"))); // NOI18N
        panelbotonMatriculas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 60));

        jPanel3.add(panelbotonMatriculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 140, 80));

        panelbotonRepresentantes.setBackground(new java.awt.Color(0, 128, 128));
        panelbotonRepresentantes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelbotonRepresentantes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelbotonRepresentantesMouseMoved(evt);
            }
        });
        panelbotonRepresentantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelbotonRepresentantesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelbotonRepresentantesMouseExited(evt);
            }
        });
        panelbotonRepresentantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Representantes");
        panelbotonRepresentantes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 34, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/repre.png"))); // NOI18N
        panelbotonRepresentantes.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 60));

        jPanel3.add(panelbotonRepresentantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 140, 80));

        panelbotonAlumnos.setBackground(new java.awt.Color(0, 128, 128));
        panelbotonAlumnos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelbotonAlumnos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelbotonAlumnosMouseMoved(evt);
            }
        });
        panelbotonAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelbotonAlumnosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelbotonAlumnosMouseExited(evt);
            }
        });
        panelbotonAlumnos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Alumnos");
        panelbotonAlumnos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 31, 80, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graduado.png"))); // NOI18N
        panelbotonAlumnos.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 60));

        jPanel3.add(panelbotonAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 140, 80));

        Distritosboton.setBackground(new java.awt.Color(0, 128, 128));
        Distritosboton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Distritosboton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(0, 128, 128));
        jPanel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel14MouseMoved(evt);
            }
        });
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel14MouseExited(evt);
            }
        });
        jPanel14.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jPanel14ComponentMoved(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Distrito Alumno");
        jPanel14.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        Distritosboton.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 2, 87, 40));

        jPanel17.setBackground(new java.awt.Color(0, 128, 128));
        jPanel17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel17MouseMoved(evt);
            }
        });
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel17MouseExited(evt);
            }
        });
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Distrito Repre");
        jPanel17.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        Distritosboton.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 48, 87, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distrito-electoral.png"))); // NOI18N
        jLabel21.setText("jLabel18");
        Distritosboton.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 60));

        jPanel3.add(Distritosboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 140, 80));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meni.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salidaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidaMouseMoved
        salida.setBackground(new Color(0, 51, 51));
        salida.setOpaque(true);
        salida.repaint();
    }//GEN-LAST:event_salidaMouseMoved

    private void salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salidaMouseClicked

    private void salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidaMouseExited
        salida.setOpaque(false);
        salida.repaint();
    }//GEN-LAST:event_salidaMouseExited

    private void RegistrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarAlumnosActionPerformed

        String dniStr = JOptionPane.showInputDialog(this, "Ingrese DNI del Alumno:");
        int dni = Integer.parseInt(dniStr);  // Convertir la entrada a int. Podría lanzar NumberFormatException.
        String nombre = JOptionPane.showInputDialog(this, "Ingrese Nombre del Alumno:");
        String apellidoPaterno = JOptionPane.showInputDialog(this, "Ingrese Apellido Paterno del Alumno:");
        String apellidoMAterno = JOptionPane.showInputDialog(this, "Ingrese Apellido Materno del Alumno:");
        String fechaNacStr = JOptionPane.showInputDialog(this, "Ingrese Fecha de Nacimiento del Alumno (AAAA-MM-DD):");
        java.util.Date fechaNac = java.sql.Date.valueOf(fechaNacStr);  // Convertir la entrada a Date. Podría lanzar IllegalArgumentException.
        String sexo = JOptionPane.showInputDialog(this, "Ingrese el sexo del estudiante");
        String Id_distritoAlumStr = JOptionPane.showInputDialog(this, "Seleccione el distrito del estudiante");
        int Id_distriroAlum = Integer.parseInt(Id_distritoAlumStr);
        String Domicilio = JOptionPane.showInputDialog(this, "Ingrese la direccion de residencia del estudiante");
        String Nivel_ing = JOptionPane.showInputDialog(this, "Ingrese el nivvel de ingreso(inicial,primaria,secudnaria)");
        String[] options = {"Inicial", "Primaria", "Secundaria"};
        int selection = JOptionPane.showOptionDialog(
            null,
            "Seleccione el nivel de ingreso",
            "Nivel de Ingreso",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            options,
            options[0]
        );

        if (selection == JOptionPane.CLOSED_OPTION) {
            return; // Salir del bloque si el usuario cerró el diálogo
        }

        Nivel_ing = options[selection];
        String Grado_ingStr = JOptionPane.showInputDialog(this, "Ingrese grado de ingreso del alumno:");
        int Grado_ing = Integer.parseInt(Grado_ingStr);
        String Colegio_ant = JOptionPane.showInputDialog(this, "Ingrese colegio de procedencia");
        String Id_habilidadStr = JOptionPane.showInputDialog(this, "Seleccione la habildiad");
        int Id_habilidad = Integer.parseInt(Id_habilidadStr);
        String Id_RepreStr = JOptionPane.showInputDialog(this, "Ingrese Id del representante");
        int Id_Repre = Integer.parseInt(Id_RepreStr);
        String Relacion = JOptionPane.showInputDialog(this, "Ingrese la relacion del representatne");
        Alumno alumno = new Alumno(dni, nombre, apellidoPaterno, apellidoMAterno, fechaNac, sexo, Id_distriroAlum, Domicilio, Nivel_ing, Grado_ing, Colegio_ant, Id_habilidad, Id_Repre, Relacion);
        AlumnoDAO alumnosDAO = new AlumnoDAO();
        boolean registroExitoso = alumnosDAO.insertar(alumno);

        if (registroExitoso) {
            JOptionPane.showMessageDialog(this, "Registro exitoso");
        } else {
            JOptionPane.showMessageDialog(this, "Error en el registro");
        }
    }//GEN-LAST:event_RegistrarAlumnosActionPerformed

    private void modificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAlumnoActionPerformed
        modificarAlumno frame = new modificarAlumno();
        System.out.println("objeto creado");
        frame.setVisible(true);
        System.out.println("frame visible");
        this.setVisible(false);
        System.out.println("ocultar");
    }//GEN-LAST:event_modificarAlumnoActionPerformed

    private void EliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAlumnoActionPerformed
        eliminarAlumno frame = new eliminarAlumno();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EliminarAlumnoActionPerformed

    private void BuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarAlumnoActionPerformed
        buscarAlumno frame = new buscarAlumno();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BuscarAlumnoActionPerformed

    private void HabilidadesAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabilidadesAlumnoActionPerformed
        habilidad frame = new habilidad();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HabilidadesAlumnoActionPerformed

    private void RegistrarRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarRepresentanteActionPerformed

        String dniRepreStr = JOptionPane.showInputDialog(this, "Ingrese DNI del Representante:");
        int dniRepre = Integer.parseInt(dniRepreStr);  // Convertir a int
        String nomRepre = JOptionPane.showInputDialog(this, "Ingrese Nombre del Representante:");
        String apePRe = JOptionPane.showInputDialog(this, "Ingrese Apellido Paterno del Representante:");
        String apeMRe = JOptionPane.showInputDialog(this, "Ingrese Apellido Materno del Representante:");
        String sexo = JOptionPane.showInputDialog(this, "Ingrese el sexo del Representante");
        String idDistritoRStr = JOptionPane.showInputDialog(this, "Ingrese ID del Distrito del Representante:");
        int idDistritoR = Integer.parseInt(idDistritoRStr);  // Convertir a int
        String domicilio = JOptionPane.showInputDialog(this, "Ingrese Domicilio del Representante:");
        String ocupacion = JOptionPane.showInputDialog(this, "Ingrese Ocupación del Representante:");
        String lugarTrabajo = JOptionPane.showInputDialog(this, "Ingrese Lugar de Trabajo del Representante:");
        String correo = JOptionPane.showInputDialog(this, "Ingrese Correo Electrónico del Representante:");
        String idTelefonoStr = JOptionPane.showInputDialog(this, "Ingrese ID de Teléfono del Representante:");
        int idTelefono = Integer.parseInt(idTelefonoStr);  // Convertir a int

        // Crea el objeto Representante
        Representante representante = new Representante(dniRepre, nomRepre, apePRe, apeMRe, sexo, idDistritoR, domicilio, ocupacion, lugarTrabajo, correo, idTelefono);

        // Instancia de la clase DAO para Representantes
        RepresentanteDAO representantesDAO = new RepresentanteDAO();

        // Intenta insertar el representante en la base de datos
        boolean registroExitoso = representantesDAO.insertar(representante);

        // Muestra un mensaje de éxito o error
        if (registroExitoso) {
            JOptionPane.showMessageDialog(this, "Registro de Representante exitoso");
        } else {
            JOptionPane.showMessageDialog(this, "Error en el registro del Representante");
        }
    }//GEN-LAST:event_RegistrarRepresentanteActionPerformed

    private void BuscarRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarRepresentanteActionPerformed
        buscarRepresentante frame = new buscarRepresentante();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BuscarRepresentanteActionPerformed

    private void modificarRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarRepresentanteActionPerformed
        modificarRepresentante frame = new modificarRepresentante();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modificarRepresentanteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        eliminarRepresentante frame = new eliminarRepresentante();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TelefonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonosActionPerformed
        telefono frame = new telefono();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TelefonosActionPerformed

    private void panelbotonAlumnosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbotonAlumnosMouseMoved
        panelbotonAlumnos.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_panelbotonAlumnosMouseMoved

    private void panelbotonRepresentantesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbotonRepresentantesMouseMoved
        panelbotonRepresentantes.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_panelbotonRepresentantesMouseMoved

    private void panelbotonMatriculasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbotonMatriculasMouseMoved
        panelbotonMatriculas.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_panelbotonMatriculasMouseMoved

    private void panelbotonAlumnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbotonAlumnosMouseExited
        panelbotonAlumnos.setBackground(new Color(0,128,128));
    }//GEN-LAST:event_panelbotonAlumnosMouseExited

    private void panelbotonRepresentantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbotonRepresentantesMouseExited
        panelbotonRepresentantes.setBackground(new Color(0,128,128));
    }//GEN-LAST:event_panelbotonRepresentantesMouseExited

    private void panelbotonMatriculasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbotonMatriculasMouseExited
        panelbotonMatriculas.setBackground(new Color(0,128,128));
    }//GEN-LAST:event_panelbotonMatriculasMouseExited

    private void panelbotonAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbotonAlumnosMouseClicked
        multimenus.setSelectedIndex(1);
    }//GEN-LAST:event_panelbotonAlumnosMouseClicked

    private void panelbotonRepresentantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbotonRepresentantesMouseClicked
        multimenus.setSelectedIndex(2);
    }//GEN-LAST:event_panelbotonRepresentantesMouseClicked

    private void jPanel14MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseMoved
        jPanel14.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jPanel14MouseMoved

    private void jPanel17MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseMoved
        jPanel17.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jPanel17MouseMoved

    private void jPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseExited
        jPanel14.setBackground(new Color(0,128,128));
    }//GEN-LAST:event_jPanel14MouseExited

    private void jPanel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseExited
        jPanel17.setBackground(new Color(0,128,128));
    }//GEN-LAST:event_jPanel17MouseExited

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed

        String idAlumnoStr = JOptionPane.showInputDialog(this, "Ingrese ID del Alumno:");
        int idAlumno = Integer.parseInt(idAlumnoStr);  // Convertir la entrada a int.
        // Opciones para los niveles de matrícula
        String[] opcionesNivel = {"Inicial", "Primaria", "Secundaria"};
        int nivelSeleccionado = JOptionPane.showOptionDialog(
            this,
            "Seleccione el nivel de matrícula:",
            "Nivel de Matrícula",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            opcionesNivel,
            opcionesNivel[0]
        );

        // Si el usuario cierra el cuadro de diálogo, terminar el método
        if (nivelSeleccionado == JOptionPane.CLOSED_OPTION) {
            return;
        }

        // Obtener el nivel de matrícula basado en la selección del usuario
        String nivelMatricula = opcionesNivel[nivelSeleccionado];
        String gradoStr = JOptionPane.showInputDialog(this, "Ingrese el grado de matrícula:");
        int grado = Integer.parseInt(gradoStr);
        //estado
        // Cuadro de diálogo para seleccionar el estado de la matrícula
        String[] opcionesEstado = {"Pagado", "Pendiente"};
        int estadoSeleccionado = JOptionPane.showOptionDialog(
            this,
            "Seleccione el estado de la matrícula:",
            "Estado de Matrícula",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            opcionesEstado,
            opcionesEstado[0]
        );

        if (estadoSeleccionado == JOptionPane.CLOSED_OPTION) {
            return;
        }
        String estadoMatricula = opcionesEstado[estadoSeleccionado];
        /////
        // Cuadro de diálogo para seleccionar el método de pago
        String[] opcionesPago = {"Efectivo", "Tarjeta"};
        int pagoSeleccionado = JOptionPane.showOptionDialog(
            this,
            "Seleccione el método de pago:",
            "Método de Pago",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            opcionesPago,
            opcionesPago[0]
        );

        if (pagoSeleccionado == JOptionPane.CLOSED_OPTION) {
            return;
        }
        String metodoPago = opcionesPago[pagoSeleccionado];
        String montoPagoStr = JOptionPane.showInputDialog(this, "Ingrese el monto del pago:");
        double montoPago = Double.parseDouble(montoPagoStr);
        String observaciones = JOptionPane.showInputDialog(this, "Ingrese observaciones si las hay:");
        String idUsuario = JOptionPane.showInputDialog(this, "Ingrese el ID del Usuario que realiza la matrícula:");

        // Crear instancia de Matricula
        Matricula matricula = new Matricula(idAlumno, nivelMatricula, grado, estadoMatricula, metodoPago, montoPago, observaciones, idUsuario);

        // Crear instancia de MatriculasDAO y registrar la matrícula
        MatriculaDAO matriculaDAO = new MatriculaDAO();
        boolean registroExitoso = matriculaDAO.insertar(matricula);

        // Mostrar mensaje de éxito o error
        if (registroExitoso) {
            JOptionPane.showMessageDialog(this, "Matrícula registrada con éxito");
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la matrícula");
        }
    }//GEN-LAST:event_RegistrarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        modificarMatricula frame = new modificarMatricula();
        frame.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_modificarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        eliminarMatricula frame = new eliminarMatricula();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar1ActionPerformed
        buscarMatricula frame = new buscarMatricula();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Buscar1ActionPerformed

    private void panelbotonMatriculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbotonMatriculasMouseClicked
        multimenus.setSelectedIndex(3);
    }//GEN-LAST:event_panelbotonMatriculasMouseClicked

    private void RegistrarDistritoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarDistritoAlumnoActionPerformed
        try {
            String distritoA = JOptionPane.showInputDialog(this, "Ingrese el nombre del distrito:");

            if (distritoA == null || distritoA.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de distrito válido.");
                return;
            }

            DistritoAlum distritoAlum = new DistritoAlum(distritoA);
            DistritoAlumDAO distritoAlumDAO = new DistritoAlumDAO();
            boolean registroExitoso = distritoAlumDAO.insertar(distritoAlum);

            if (registroExitoso) {
                JOptionPane.showMessageDialog(this, "Registro de distrito exitoso");
            } else {
                JOptionPane.showMessageDialog(this, "Error en el registro de distrito");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al ingresar datos numéricos.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en el registro: " + e.getMessage());
        }
    }//GEN-LAST:event_RegistrarDistritoAlumnoActionPerformed

    private void modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar1ActionPerformed
        modificarDistritoAlum frame = new modificarDistritoAlum();

        frame.setVisible(true);

        this.setVisible(false);

    }//GEN-LAST:event_modificar1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        eliminarDistritoAlum frame = new eliminarDistritoAlum();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar2ActionPerformed
        buscarDistritoAlum frame = new buscarDistritoAlum();
        frame.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_Buscar2ActionPerformed

    private void jPanel14ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel14ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14ComponentMoved

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        multimenus.setSelectedIndex(4);
    }//GEN-LAST:event_jPanel14MouseClicked

    private void Registrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar2ActionPerformed
        try {
            String distritoR = JOptionPane.showInputDialog(this, "Ingrese el nombre del distrito:");

            if (distritoR == null || distritoR.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de distrito válido.");
                return;
            }

            DistritoRepre distritoRepre = new DistritoRepre(distritoR);
            DistritoRepreDAO distritoRepreDAO = new DistritoRepreDAO();
            boolean registroExitoso = distritoRepreDAO.insertar(distritoRepre);

            if (registroExitoso) {
                JOptionPane.showMessageDialog(this, "Registro de distrito exitoso");
            } else {
                JOptionPane.showMessageDialog(this, "Error en el registro de distrito");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al ingresar datos numéricos.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en el registro: " + e.getMessage());
        }
    }//GEN-LAST:event_Registrar2ActionPerformed

    private void modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar2ActionPerformed
        modificarDistritoRepre frame = new modificarDistritoRepre();

        frame.setVisible(true);

        this.setVisible(false);

    }//GEN-LAST:event_modificar2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        eliminarDistritoRepre frame = new eliminarDistritoRepre();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Buscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar3ActionPerformed
        buscarDistritoRepre frame = new buscarDistritoRepre();
        frame.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_Buscar3ActionPerformed

    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked
        multimenus.setSelectedIndex(5);
    }//GEN-LAST:event_jPanel17MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        consultaralumnos();
        JOptionPane.showMessageDialog(null, "Actualizado!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        consultarRepresentantes();
        JOptionPane.showMessageDialog(null, "Actualizado!");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        consultarMatriculas();
        JOptionPane.showMessageDialog(null, "Actualizado!");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        consultarDistritosalum();
        JOptionPane.showMessageDialog(null, "Actualizado!");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        consultarDistritosrepres();
        JOptionPane.showMessageDialog(null, "Actualizado!");
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuunitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuunitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuunitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuunitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuunitario().setVisible(true);
            }
        });
    }
    void consultaralumnos() {
        // Crear una instancia de AlumnoDAO
        AlumnoDAO alumnoDAO = new AlumnoDAO();

        // Obtener la lista de todos los alumnos
        List<Alumno> listaAlumnos = alumnoDAO.obtenerTodosLosAlumnos();

        // Limpia las filas existentes en la tabla
        DefaultTableModel modeloAlumnos = (DefaultTableModel) Tabla.getModel();
        while (modeloAlumnos.getRowCount() > 0) {
            modeloAlumnos.removeRow(0);
        }

        // Iterar sobre la lista de alumnos y agregarlos a la tabla
        for (Alumno alumno : listaAlumnos) {
            Object[] estudiante = new Object[]{
                alumno.getId_Alumno(),
                alumno.getNom_Alu(),
                alumno.getApe_MAl(),
                alumno.getApe_PAl(),
                alumno.getDni_Alumno()
            };
            modeloAlumnos.addRow(estudiante);
        }

        Tabla.setModel(modeloAlumnos);
    }
    void consultarRepresentantes() {
        // Crear una instancia para obtener los representantes
        // Asumo que tienes una clase similar para representantes como la que tenías para alumnos
        RepresentanteDAO representanteDAO = new RepresentanteDAO();

        // Obtener la lista de todos los representantes
        List<Representante> listaRepresentantes = representanteDAO.obtenerTodosLosRepresentantes();

        // Limpia las filas existentes en la tabla
        DefaultTableModel modeloRepresentantes = (DefaultTableModel) Tabla2.getModel();
        while (modeloRepresentantes.getRowCount() > 0) {
            modeloRepresentantes.removeRow(0);
        }

        // Iterar sobre la lista de representantes y agregarlos a la tabla
        for (Representante representante : listaRepresentantes) {
            Object[] datosRepresentante = new Object[]{
                representante.getId_Repre(),
                representante.getNom_Repre(),
                representante.getApe_PRe(),
                representante.getApe_MRe(),
                representante.getDni_Repre(), // Aquí puedes agregar más campos según lo que quieras mostrar en la tabla
            // Por ejemplo: representante.getSexo(), representante.getOcupacion(), etc.
            };
            modeloRepresentantes.addRow(datosRepresentante);
        }

        Tabla2.setModel(modeloRepresentantes);
    }
    void consultarMatriculas() {

        MatriculaDAO matriculaDAO = new MatriculaDAO();
        List<Matricula> listaMatriculas = matriculaDAO.obtenerTodasLasMatriculas();
        DefaultTableModel modeloMatriculaswa = (DefaultTableModel) TablaMatriculas.getModel();
        while (modeloMatriculaswa.getRowCount() > 0) {
            modeloMatriculaswa.removeRow(0);
        }

        // Iterar sobre la lista de alumnos y agregarlos a la tabla
        for (Matricula matricula : listaMatriculas) {
            Object[] estudiante = new Object[]{
                matricula.getId_Matricula(),
                matricula.getId_Alumno(),
                matricula.getNivel_m(),
                matricula.getGrado_m(),
                matricula.getEstado_m(),
                matricula.getMetodo_Pago(),
                matricula.getMonto_Pago()
            };
            modeloMatriculaswa.addRow(estudiante);
        }

        TablaMatriculas.setModel(modeloMatriculaswa);
    }
    void consultarDistritosalum() {
        DistritoAlumDAO distritoDAO = new DistritoAlumDAO();

        // Obtener la lista de todos los distritos
        List<DistritoAlum> listaDistritos = distritoDAO.obtenerDistritos();

        // Limpia las filas existentes en la tabla
        DefaultTableModel modelotablaalumdistrict = (DefaultTableModel) TablaDistritoAlum.getModel();
        while (modelotablaalumdistrict.getRowCount() > 0) {
            modelotablaalumdistrict.removeRow(0);
        }

        // Iterar sobre la lista de distritos y agregarlos a la tabla
        for (DistritoAlum distrito : listaDistritos) {
            Object[] filaDistrito = new Object[]{
                distrito.getId_distritoAlum(), // Aquí debes usar el método adecuado para obtener el ID del distrito
                distrito.getDistritoA() // Aquí debes usar el método adecuado para obtener el nombre del distrito
            };
            modelotablaalumdistrict.addRow(filaDistrito);
        }

        TablaDistritoAlum.setModel(modelotablaalumdistrict);
    }
    void consultarDistritosrepres() {
        DistritoRepreDAO distritoDAO = new DistritoRepreDAO();

        // Obtener la lista de todos los distritos
        List<DistritoRepre> listaDistritos = distritoDAO.obtenerDistritos();

        // Limpia las filas existentes en la tabla
        DefaultTableModel modelodistrictrepre = (DefaultTableModel) tabladistritorepre.getModel();
        while (modelodistrictrepre.getRowCount() > 0) {
            modelodistrictrepre.removeRow(0);
        }

        // Iterar sobre la lista de distritos y agregarlos a la tabla
        for (DistritoRepre distrito : listaDistritos) {
            Object[] filaDistrito = new Object[]{
                distrito.getId_distritoRepre(), // Aquí debes usar el método adecuado para obtener el ID del distrito
                distrito.getDistritoR() // Aquí debes usar el método adecuado para obtener el nombre del distrito
            };
            modelodistrictrepre.addRow(filaDistrito);
        }

        tabladistritorepre.setModel(modelodistrictrepre);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar1;
    private javax.swing.JButton Buscar2;
    private javax.swing.JButton Buscar3;
    private javax.swing.JButton BuscarAlumno;
    private javax.swing.JButton BuscarRepresentante;
    private javax.swing.JPanel Distritosboton;
    private javax.swing.JButton EliminarAlumno;
    private javax.swing.JButton HabilidadesAlumno;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton Registrar2;
    private javax.swing.JButton RegistrarAlumnos;
    private javax.swing.JButton RegistrarDistritoAlumno;
    private javax.swing.JButton RegistrarRepresentante;
    private javax.swing.JTable Tabla;
    private javax.swing.JTable Tabla2;
    private javax.swing.JTable TablaDistritoAlum;
    private javax.swing.JTable TablaMatriculas;
    private javax.swing.JButton Telefonos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton modificar;
    private javax.swing.JButton modificar1;
    private javax.swing.JButton modificar2;
    private javax.swing.JButton modificarAlumno;
    private javax.swing.JButton modificarRepresentante;
    private javax.swing.JTabbedPane multimenus;
    private javax.swing.JPanel panelbotonAlumnos;
    private javax.swing.JPanel panelbotonMatriculas;
    private javax.swing.JPanel panelbotonRepresentantes;
    private javax.swing.JPanel salida;
    private javax.swing.JTable tabladistritorepre;
    // End of variables declaration//GEN-END:variables
}
